/*
 * FailFileFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.blackgray.douban.album.download.ui;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.Map.Entry;

import javax.swing.KeyStroke;

import cn.blackgray.douban.album.download.common.Console;
import cn.blackgray.douban.album.download.common.utils.CommonUtils;
import cn.blackgray.douban.album.download.service.creator.HtmlCreator;
import cn.blackgray.douban.album.download.service.download.DownloadFailManager;

/**
 * 失败文件下载界面
 */
public class FailFileFrame extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;

	/** Creates new form FailFileFrame */
	private FailFileFrame() {
		initComponents();
		init();
		this.setTitle("下载失败文件列表");
		this.setLocationRelativeTo(MainFrame.getInstance());
	}

	/**
	 * 初始化
	 */
	private void init() {
		//设置macos下快捷键
		if (CommonUtils.isMacOS()) {
			int MASK = Toolkit.getDefaultToolkit().getMenuShortcutKeyMask();
			//控件设置快捷键
			failFileInfoTextArea.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_A, MASK), "select-all");
			failFileInfoTextArea.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_C, MASK), "copy");
			failFileInfoTextArea.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_X, MASK), "cut");
			failFileInfoTextArea.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_V, MASK), "paste");
		}
		
		//显示失败文件列表
		failFileInfoTextArea.setText("");
		for (Entry<String, String> image : DownloadFailManager.getFailFileMap().entrySet()) {
			failFileInfoTextArea.append("下载失败：" + image.getKey() + " ——> "
					+ image.getValue() + "\r\n");
		}
		//显示文件个数
		countLabel.setText(String.valueOf(DownloadFailManager.getFailSize()));
	}

	private static FailFileFrame instance = null;
	private static List<String> finishedAlbumPathList = null;

	public static FailFileFrame getInstance() {
		if (instance == null) {
			instance = new FailFileFrame();
		}
		return instance;
	}
	
	public static FailFileFrame getInstance(List<String> finishedAlbumPathList) {
		FailFileFrame.finishedAlbumPathList = finishedAlbumPathList;
		return getInstance();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		javax.swing.JButton reloadBtn = new javax.swing.JButton();
		javax.swing.JButton cancelButton = new javax.swing.JButton();
		javax.swing.JLabel cLabel = new javax.swing.JLabel();
		javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
		failFileInfoTextArea = new javax.swing.JTextArea();
		countLabel = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});

		reloadBtn.setText("\u91cd\u65b0\u4e0b\u8f7d");
		reloadBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				reloadBtnActionPerformed(evt);
			}
		});

		cancelButton.setText("\u53d6\u6d88");
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelButtonActionPerformed(evt);
			}
		});

		cLabel.setText("\u6587\u4ef6\u4e2a\u6570\uff1a");

		failFileInfoTextArea.setColumns(20);
		failFileInfoTextArea.setRows(5);
		jScrollPane1.setViewportView(failFileInfoTextArea);

		countLabel.setText("0");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		reloadBtn,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		183,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		cancelButton,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		181,
																		Short.MAX_VALUE))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		cLabel)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		countLabel))
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														376, Short.MAX_VALUE))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(cLabel)
												.addComponent(countLabel))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										197, Short.MAX_VALUE)
								.addGap(19, 19, 19)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(reloadBtn)
												.addComponent(cancelButton))
								.addGap(23, 23, 23)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void formWindowClosing(java.awt.event.WindowEvent evt) {
		System.out.println("FailFileFrame.formWindowClosing()");
		closeWindow();
	}

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
		closeWindow();
	}

	/**
	 * 关闭窗口
	 * 关闭后执行网页文档创建操作
	 */
	private void closeWindow(){
		this.setVisible(false);
		//生成下载失败记录文件
		createFailFileDoc();
		//生成网页
		createAlbumHTML();
		
		//清空失败文件集合
		DownloadFailManager.clearAll();
		//重置已完成下载的相册的路径集合
		FailFileFrame.finishedAlbumPathList = null;
		
		Console.print("【FINISH】");
	}
	
	/**
	 * 生成网页
	 */
	private void createAlbumHTML(){
		//创建文档
		if (FailFileFrame.finishedAlbumPathList != null && FailFileFrame.finishedAlbumPathList.size() != 0) {
			Console.print("【正在生成HTML文档,请稍等...】");
			HtmlCreator.createAlbumHTML(finishedAlbumPathList);
			Console.print("【HTML文档生成成功】");
			//设置界面下载按钮可用
			MainFrame.getInstance().downloadBtn.setEnabled(true);
		}
	}
	
	/**
	 * 生成下载失败记录文件
	 */
	private void createFailFileDoc(){
		//若关闭窗口、取消下载时，仍有失败文件，生成下载失败记录文档
		if (DownloadFailManager.getFailSize() != 0) {
			Console.print("【正在生成下载失败图片记录文档...】");
			DownloadFailManager.createAlbumFailFileDoc(finishedAlbumPathList, DownloadFailManager.getFailFileMap());
			Console.print("【下载失败图片记录文档生成成功】");
		}
		
	}
	
	/**
	 * 重试下载失败文件
	 * @param evt
	 */
	private void reloadBtnActionPerformed(java.awt.event.ActionEvent evt) {
		new Thread(new Runnable() {

			@Override
			public void run() {
				//重新下载
				FailFileFrame.getInstance().setVisible(false);
				boolean success = DownloadFailManager.downloadFailFile();
				if (success) {
					//全部下载成功，生成网页、界面重置
					//生成网页
					createAlbumHTML();
					//设置界面下载按钮可用
					MainFrame.getInstance().downloadBtn.setEnabled(true);
					Console.print("【FINISH】");
				}else{
					//未全部下载，重新显示失败文件下载界面
					FailFileFrame.getInstance().init();
					FailFileFrame.getInstance().setVisible(true);		
				}
			}
		}).start();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FailFileFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	javax.swing.JLabel countLabel;
	javax.swing.JTextArea failFileInfoTextArea;
	// End of variables declaration//GEN-END:variables


}